[project]
name = "openpluginloader"
version = "0.1.0"
description = "A plugin loader library meant for wide use and quick adoption."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mypy>=2.3.1",
    "packaging>=26.3",
]

[project.scripts]
archive-plugin = "openpluginloader.__main__:archive_plugin"
build-plugin = "openpluginloader.__main__:archive_plugin"